const orange = "#006400";
const textLight = "#eaf2f4";

export const register = (theme) => ({
  main: {
    marginTop: theme.spacing(8),
    marginBottom: theme.spacing(4),
    marginRight: theme.spacing(3),
    marginLeft: theme.spacing(3),
    display: "block",
    width: "auto",
    [theme.breakpoints.up(600 + theme.spacing(2))]: {
      width: 600,
      marginLeft: "auto",
      marginRight: "auto",
      direction: "rtl",
    },
  },
  paper: {
    position: "relative",
    marginTop: theme.spacing(2),
    padding: `${theme.spacing(2)}px ${theme.spacing(4)}px`,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    direction: "rtl",
    background: "#ffffff" /* تغيير الخلفية إلى الأبيض */,
    border: "2px solid #077513ad" /* تغيير لون الحواف إلى الأخضر */,
    boxShadow: ".2px 12px 18px rgba(131,153,167,0.6)",
    "&:hover": {
      boxShadow: "0px 24px 36px rgba(131,153,167,0.99)",
    },
  },
  form: {
    margin: `${theme.spacing(4)}px 0`,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    direction: "rtl",
  },
  inputContainer: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: theme.spacing(2),
    direction: "rtl",
  },
  labels: {
    flex: 1,
    padding: `${theme.spacing(1)}px ${theme.spacing(1)}px`,
    fontSize: "14px",
    fontFamily: "PT Mono, monospace",
    fontWeight: 800,
    opacity: 0.45,
    color: "black",
    textAlign: "right",
    direction: "rtl",
  },
  inputs: {
    flex: 2,
    marginLeft: theme.spacing(1),
    marginRight: theme.spacing(1),
    fontFamily: "Cutive Mono, monospace",
    color: "black",
    fontSize: "14px",
    padding: `${theme.spacing(1.5)}px ${theme.spacing(1)}px`,
    borderRadius: "8px",
    border: "1.4px solid",
    boxShadow: "1px 2px 20px rgba(169,198,217,0.29457423) ",
    borderColor: "rgba(206,212,218, .993)",
    direction: "rtl",
    "&:hover": {
      background: "rgba(169,198,217,0.36457423) ",
    },
  },
  button: {
    color: "black",
    background: "rgba(255,255,255,.45)",
    position: "relative",
    fontWeight: 400,
    fontFamily: "Raleway, sans-serif",
    overflow: "hidden",
    marginTop: theme.spacing(6),
    padding: `${theme.spacing(1.6)}px`,
    border: "none",
    borderRadius: "8px",
    letterSpacing: "3px",
    direction: "rtl",
    "&::before, &::after": {
      position: "absolute",
      content: '""',
      boxSizing: "border-box",
      borderRadius: "8px",
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      opacity: 1,
    },
    "&::before": {
      borderBottom: `2px solid gray`,
      borderTop: `2px solid gray`,
      transform: "scale(0,1)",
    },
    "&::after": {
      borderLeft: `3px solid gray`,
      borderRight: `3px solid gray`,
      transform: "scale(1,0)",
    },
    "&:hover::before": {
      transform: "scale(1,1)",
      transition: "transform cubic-bezier(0.85,.36,.8,.42) 0.3s",
    },
    "&:hover::after": {
      transform: "scale(1,1)",
      transition: "transform cubic-bezier(0.85,.36,.8,.42) .2s",
    },
    "&::first-letter": {
      color: orange,
    },
    "&:hover": {
      background: "rgba(169,198,217,0.8)",
      color: textLight,
    },
  },
  error: {
    border: `1.2px solid gray`,
    background: "rgba(169,198,217,0.29457423)",
    color: "gray",
    fontSize: "14px",
    fontWeight: 400,
    fontFamily: "Raleway, sans-serif",
    display: "flex",
    alignItems: "center",
    paddingBottom: theme.spacing(3),
  },
  radioContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  radioLabel: {
    fontFamily: "Cutive Mono, monospace",
    fontSize: "14px",
    marginLeft: theme.spacing(1),
    marginRight: theme.spacing(2),
    color: "black",
  },
  passwordEye: {
    color: "black",
    opacity: 0.7,
  },
});
